<h3>NumPy (short form of Numerical Python) is an open-source Python library used for
numerical computing. It provides tools for working efficiently with arrays, matrices, and
mathematical functions.</h3>
<h3>NumPy introduces a new data structure called the ndarray (n-dimensional array),
which is much faster and more memory-efficient than Python’s built-in lists for
numerical operations.</h3>

In [2]:
import numpy as np

arr = np.array([1,2,3,"Hello"])
arr

array(['1', '2', '3', 'Hello'], dtype='<U21')

In [3]:
#To get size of array
arr.nbytes

336

In [4]:
#Type of array
type(arr)

numpy.ndarray

In [5]:
#Shape of array returns in tuple the dimension
arr.shape

(4,)

<h2>Using Bultin Functions lets create ndarray</h2>

In [6]:
#Create arr of (row,col) dimension with 0 values

zerosArr = np.zeros((2,3))
print(zerosArr)

#Creating arr of (row,col) dimension with 1 value

oneArr = np.ones((3,3))
print(oneArr)


#Creating arr of (row,col) dimension with any value

mat = np.full((2,2),5)
print(mat)

#Creating Identity matrix
id_mat = np.eye(3)
print(id_mat)

arr5 = np.arange(1, 20, 2) # Elements in range(1, 20)
print(arr5, arr5.shape)
arr6 = np.linspace(0, 10, 5) # Evenly spaced array
print(arr6, arr6.shape)
print(arr6.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  3  5  7  9 11 13 15 17 19] (10,)
[ 0.   2.5  5.   7.5 10. ] (5,)
1



<h4>💡 In short:</h4>
<h5>The formal meaning: (3,3,4) → lengths along axes 0, 1, 2.</h5>
<h5>The analogy explanation: “blocks, rows, columns” → just a way to help you visualize the 3D shape.</h5>

In [7]:
import numpy as np
arr = np.zeros((3, 3, 4))


In [8]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [9]:
#Create arr of (row,col) dimension with 0 values

zerosArr = np.zeros((2,3,3))
print(zerosArr)

#Creating arr of (row,col) dimension with 1 value

oneArr = np.ones((3,3,3))
print(oneArr)


#Creating arr of (row,col) dimension with any value

mat = np.full((2,2,6),5)
print(mat)

#Creating Identity matrix
id_mat = np.eye(3)
print(id_mat)

arr5 = np.arange(1, 20, 2) # Elements in range(1, 20)
print(arr5, arr5.shape)
arr6 = np.linspace(0, 10, 5) # Evenly spaced array
print(arr6, arr6.shape)
print(arr6.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[5 5 5 5 5 5]
  [5 5 5 5 5 5]]

 [[5 5 5 5 5 5]
  [5 5 5 5 5 5]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  3  5  7  9 11 13 15 17 19] (10,)
[ 0.   2.5  5.   7.5 10. ] (5,)
1


In [10]:
n_arr = np.array([[1,2,3],[4,5,6]])
n_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
n_arr.ndim

2

In [12]:
#To get sum of entire array
arr1 = np.array([1,2,3,4,5])
print(np.sum(arr1))

15


In [13]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr2))

21


In [14]:
sum_of_cols = np.sum(arr2,0)
sum_of_cols

array([5, 7, 9])

In [15]:
sum_of_rows = np.sum(arr2,axis=1)
sum_of_rows

array([ 6, 15])

In [16]:
print(arr2[0,2])

3


In [17]:
#Scling of 2d array
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
print(arr2[0:2,0:2])

[[1 2]
 [4 5]]


<h2>Datatypes in Numpy</h2>

| **Category** | **Examples** | **Description** |
| --- | --- | --- |
| **Boolean** | ``np.bool_`` | Stores ``True``/``False`` values (1 byte). |
| **Signed Integers** | ``np.int8``, ``np.int16``, ``np.int32``, ``np.int64`` | Fixed-width integers (8–64 bits). |
| **Unsigned Integers** | ``np.uint8``, ``np.uint16``, ``np.uint32``, ``np.uint64`` | Non-negative integers (8–64 bits). |
| **Floating Point** | ``np.float16``, ``np.float32``, ``np.float64`` | Decimal numbers with varying precision. |
| **Complex Numbers** | ``np.complex64``, ``np.complex128`` | Complex values with real + imaginary parts. |
| **String/Unicode** | ``np.string_``, ``np.unicode_`` | Fixed-length text storage. |
| **Object** | ``np.object_`` | Stores arbitrary Python objects. |
| **Datetime/Timedelta** | ``np.datetime64``, ``np.timedelta64`` | Dates, times, and durations. |

In [21]:
a1 = np.array([1,2,3,4,5])
print(a1.dtype)

a2 = np.array(["hello","world"])
print(a2.dtype)

a3 = np.array([88.60,90.15])
print(a3.dtype)

a4 = np.array([True,False])
print(a4.dtype)

int64
<U5
float64
bool


## 🌟 Why Dtypes Matter in NumPy

### 1. **Memory Efficiency**
- Each dtype uses a fixed number of bytes per element.
- Example:  
  - `np.int8` → **1 byte per element**  
  - `np.int64` → **8 bytes per element**  
- Choosing smaller dtypes saves memory, especially for large arrays.

---

### 2. **Performance**
- Smaller dtypes mean fewer bits to process → faster computations.
- Example: Using `float32` instead of `float64` can speed up numerical operations when high precision isn’t required.

---

### 3. **Compatibility**
- Many external libraries expect specific dtypes:
  - **Images** → usually stored as `np.uint8` (values 0–255).  
  - **Machine Learning frameworks** → often expect `float32` for tensors.  
- Picking the right dtype ensures smooth interoperability.

---

## ⚡ Quick Example
```python
import numpy as np

# Memory efficiency
arr_int8 = np.array([1, 2, 3], dtype=np.int8)
arr_int64 = np.array([1, 2, 3], dtype=np.int64)

print(arr_int8.nbytes)   # 3 bytes
print(arr_int64.nbytes)  # 24 bytes

# Performance & compatibility
img = np.array([[255, 128, 0]], dtype=np.uint8)   # image pixel values
tensor = np.array([1.2, 3.4, 5.6], dtype=np.float32)  # ML tensor
```

**Vectorization and broadcasting are two core ideas in NumPy that make array operations fast and expressive: vectorization replaces explicit Python loops with compiled C-level operations, while broadcasting allows arrays of different shapes to interact seamlessly. Together, they enable concise, memory-efficient, and high-performance numerical code.**

---

## ⚡ Vectorization in NumPy
- **Definition**: Vectorization means applying operations directly on entire arrays instead of looping element by element in Python.
- **Why it matters**:
  - **Speed**: Operations run in optimized C code, often **50–100× faster** than Python loops.
  - **Simplicity**: Cleaner, shorter code.
  - **Consistency**: Works across scalars, vectors, and matrices.
- **Example**:
  ```python
  import numpy as np

  a = np.array([1, 2, 3, 4])
  b = np.array([10, 20, 30, 40])

  # Vectorized addition
  result = a + b   # [11, 22, 33, 44]

  # Instead of looping:
  # for i in range(len(a)):
  #     result[i] = a[i] + b[i]
  ```

---

## 📐 Broadcasting in NumPy
- **Definition**: Broadcasting describes how NumPy handles arrays of different shapes during arithmetic operations by “stretching” the smaller array to match the larger one.
- **Rules**:
  1. Compare shapes from **right to left**.
  2. Dimensions are compatible if they are equal or one of them is **1**.
  3. If not compatible, NumPy raises a `ValueError`.
- **Examples**:
  ```python
  # Scalar with array
  a = np.array([1.0, 2.0, 3.0])
  b = 2.0
  print(a * b)   # [2.0, 4.0, 6.0]

  # 2D with 1D
  M = np.array([[1, 2, 3],
                [4, 5, 6]])
  v = np.array([10, 20, 30])
  print(M + v)
  # [[11, 22, 33],
  #  [14, 25, 36]]
  ```

---

## 🔑 Key Benefits
- **Vectorization**:
  - Eliminates Python loops.
  - Uses CPU vector instructions for speed.
- **Broadcasting**:
  - Avoids unnecessary data replication.
  - Enables flexible operations across mismatched shapes.
  - Saves memory and improves readability.

---

## ⚠️ Considerations
- **Memory inefficiency**: Broadcasting can lead to large temporary arrays if shapes expand significantly.
- **Precision trade-offs**: Vectorization often uses fixed dtypes (`float32`, `float64`), so be mindful of accuracy.
- **Debugging**: Shape mismatches can cause subtle errors; always check `.shape`.

## 🧩 Shapes in the Example
- Array A: shape **(2,3)**  
- Array B: shape **(3,)**  

---

## 📐 Step 1: Pad the smaller shape
NumPy compares shapes from **right to left**.  
- A: `(2,3)`  
- B: `(3,)` → padded to `(1,3)`  

Now both have 2 dimensions: `(2,3)` vs `(1,3)`.

---

## 📐 Step 2: Compare dimensions
- Last dimension: `3 vs 3` → ✅ match.  
- First dimension: `2 vs 1` → ✅ compatible, because `1` can stretch to `2`.

---

## 📐 Step 3: Stretch the `1`
- `(1,3)` stretches to `(2,3)` to match A.  
- Resulting shape: `(2,3)`.

---

## 🔎 Intuition
Think of `(3,)` as a **row vector**.  
- Padding makes it `(1,3)` → one row, three columns.  
- When added to `(2,3)`, that single row is **copied twice** (stretched) to match the two rows.  

So the operation works element-wise across both rows.

---

## ✅ Example in Code
```python
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2,3)

B = np.array([10, 20, 30])  # shape (3,)

print(A + B)
# [[11 22 33]
#  [14 25 36]]
```

In [22]:
num1 = np.array([1,2,3])
num2 = np.array([4,5,6])

print(num1+num2)


[5 7 9]


In [23]:
sq_num1 = num1**2
print(sq_num1)

[1 4 9]


In [24]:
# Broadcasting with a Vector
arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1D + arr2D)

[[2 4 6]
 [5 7 9]]


## Aggregation Functions
These reduce an array to a single value (or smaller array):

1. `np.sum()` → sum of all elements  
2. `np.prod()` → product of all elements  
3. `np.min()` → minimum value  
4. `np.max()` → maximum value  
5. `np.argmin()` → index of min value  
6. `np.argmax()` → index of max value  
7. `np.mean()` → mean (average)  
8. `np.median()` → median  
9. `np.std()` → standard deviation  
10. `np.var()` → variance  

```python
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))      # 15
print(np.prod(arr))     # 120
print(np.min(arr))      # 1
print(np.max(arr))      # 5
print(np.argmin(arr))   # 0
print(np.argmax(arr))   # 4
print(np.mean(arr))     # 3.0
print(np.median(arr))   # 3.0
print(np.std(arr))      # 1.41
print(np.var(arr))      # 2.0
```

In [28]:
nums = [1,2,3,4,5,6,7,8,9,10]
print("mean = ",np.mean(nums))
print("Sum =",np.sum(nums))
print("product =",np.prod(nums))
print("Median =",np.median(nums))
print("Standard Deviation =",np.std(nums))
print("Variance =",np.var(nums))
print("Min Value =",np.min(nums))
print("max Value =",np.max(nums))
print("Min Value Index =",np.argmin(nums))
print("max Value Index =",np.argmax(nums))

mean =  5.5
Sum = 55
product = 3628800
Median = 5.5
Standard Deviation = 2.8722813232690143
Variance = 8.25
Min Value = 1
max Value = 10
Min Value Index = 0
max Value Index = 9


In [30]:
mat = np.array([[1,2,3],
                [4,5,6]])

print(np.prod(mat))

720


## ✨ Power Functions
1. `np.square()` → square of all elements  
2. `np.sqrt()` → square root of all elements  
3. `np.cbrt()` → cube root of all elements  
4. `np.pow(arr, n)` → raise elements to power `n`

```python
arr = np.array([1, 2, 3, 4, 5])

print(np.square(arr))  # [1, 4, 9, 16, 25]
print(np.sqrt(arr))    # [1, 1.41, 1.73, 2, 2.23]
print(np.pow(arr, 3))  # [1, 8, 27, 64, 125]
```

## 📈 Log & Exponential Functions
1. `np.log()` → natural log (base e)  
2. `np.log10()` → log base 10  
3. `np.log2()` → log base 2  
4. `np.exp()` → exponential \(e^x\)

```python
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))
```

## 🔄 Rounding Functions
1. `np.round()` → round to nearest  
2. `np.ceil()` → round up  
3. `np.floor()` → round down  
4. `np.trunc()` → remove fractional part  

```python
print(np.round(2.678))  # 3.0
print(np.floor(2.678))  # 2.0
print(np.ceil(2.678))   # 3.0
print(np.trunc(2.678))  # 2.0
```

## 🎯 Miscellaneous Functions
1. `np.abs()` → absolute values  
2. `np.sort()` → sorted values  
3. `np.unique()` → unique values  

```python
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5])

print(np.abs(arr))    # [1 2 5 3 8 4 2 5]
print(np.sort(arr))   # [-5 -4 1 2 2 3 5 8]
print(np.unique(arr)) # [-5 -4 1 2 3 5 8]
```

## 🎲 `np.random.random`
- **Purpose**: Generates random **floating-point numbers** between **0.0 and 1.0**.
- **Range**: Always `[0.0, 1.0)`.
- **Type**: `float`.
- **Usage**:
  ```python
  import numpy as np

  # Single random float
  print(np.random.random())  
  # Example: 0.374

  # Array of random floats
  print(np.random.random((2,3)))
  # Example:
  # [[0.12 0.89 0.45]
  #  [0.67 0.23 0.91]]
  ```

---

## 🎲 `np.random.randint`
- **Purpose**: Generates random **integers** within a specified range.
- **Range**: `[low, high)` → includes `low`, excludes `high`.
- **Type**: `int`.
- **Usage**:
  ```python
  # Single random integer between 1 and 10
  print(np.random.randint(1, 10))  
  # Example: 7

  # Array of random integers
  print(np.random.randint(1, 10, size=(2,3)))
  # Example:
  # [[3 9 1]
  #  [7 2 8]]
  ```

---

## 🔑 Key Differences

| Feature              | `np.random.random` | `np.random.randint` |
|----------------------|---------------------|----------------------|
| Output type          | Float              | Integer             |
| Range                | [0.0, 1.0)         | [low, high)         |
| Parameters           | `size`             | `low`, `high`, `size` |
| Typical use case     | Probabilities, scaling, ML initialization | Discrete sampling, indexing, simulations |