# NumPy Assignment — 50 Questions
### Easy (20) · Medium (20) · Hard (10)

This assignment builds directly on what you covered in `Numpy_Basics.ipynb` — array creation, shape/dtype/ndim, indexing & slicing, broadcasting, vectorization, and aggregation/power/log/rounding functions.

The **Medium** and **Hard** sections also introduce a handful of natural next-step tools you haven't formally covered yet (`reshape`, `stack`/`concatenate`, boolean masking, `np.where`, `np.dot`/`@`). Each of these comes with a hint explaining the function the first time it's needed — treat it as a small extension of what you already know, not a prerequisite you're missing.

**Instructions:**
- Attempt every question yourself before checking any hint.
- Write your solution in the `# Your code here` cell provided.
- Print your output so you can verify it against the expected result described in the question.
- For the **Hard** section, a collapsible solution is provided at the end of each question — try not to peek until you've genuinely attempted it.
- Restart & Run All before submitting, to confirm everything executes top to bottom without errors.


In [1]:
import numpy as np

# Run this cell first — it's used by several questions below
np.random.seed(42)


---
## 🟢 Section 1: Easy (Q1 – Q20)

Basic syntax and single-concept operations — array creation, attributes, indexing/slicing, dtypes, and simple aggregations.


**Q1. Create a 1D array**

Create a 1D NumPy array called `arr1` from the list `[10, 20, 30, 40, 50]`. Print its `type`, `shape`, and `ndim`.

In [2]:
# Your code here

arr1 = np.array([10,20,30,40,50])
print(type(arr1))
print(arr1.shape)
print(arr1.ndim)

<class 'numpy.ndarray'>
(5,)
1


**Q2. Create a 2D array**

Create a 2D array called `arr2` representing the matrix `[[1, 2, 3], [4, 5, 6]]`. Print its `shape` and `ndim`.

In [3]:
# Your code here
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.shape)
print(arr2.ndim)


(2, 3)
2


**Q3. Zeros array**

Create an array of shape `(4, 5)` filled with zeros using `np.zeros()`. Print it.

In [4]:
# Your code here
Z = np.zeros((4,5))
Z


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Q4. Ones array and sum**

Create an array of shape `(3, 3)` filled with ones using `np.ones()`. Print the sum of all its elements (should be `9`).

In [5]:
# Your code here

ones_arr = np.ones((3,3))

print(ones_arr)
print(np.sum(ones_arr))


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
9.0


**Q5. Full array with a custom value**

Use `np.full()` to create a `(2, 4)` array where every element is `7`.

In [6]:
# Your code here

a = np.full((2,4),7)
a


array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

**Q6. Identity matrix**

Create a `5x5` identity matrix using `np.eye()` and print it.

In [7]:
# Your code here

id_mat = np.eye(5)
id_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Q7. arange with step**

Use `np.arange()` to create an array of all even numbers from `2` to `30` (inclusive). Print the array and its shape.

In [8]:
# Your code here

even_eles = np.arange(2,32,2)
even_eles

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

**Q8. linspace**

Use `np.linspace()` to create an array of `6` evenly spaced numbers between `0` and `1` (inclusive of both ends).

In [9]:
# Your code here
b = np.linspace(0,1,6)
b


array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

**Q9. Element access in 2D array**

Given `matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])`, print the element in row `1`, column `2` (should be `60`).

In [10]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Your code here
matrix[1,2]


np.int64(60)

**Q10. Slicing a 2D array**

Using the same `matrix` from Q9, slice out the top-left `2x2` sub-matrix `[[10, 20], [40, 50]]` using slicing syntax.

In [11]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Your code here

matrix[0:2,0:2]

array([[10, 20],
       [40, 50]])

**Q11. Check dtype**

Create an array from `[1.5, 2.5, 3.5]` and print its `dtype`. What dtype do you expect before running it?

In [12]:
# Your code here
c = np.array([1.5,2.5,3.5])
print(c.dtype)


float64


**Q12. Changing dtype with astype**

Given `arr = np.array([1.9, 2.1, 3.7])`, convert it to an integer array using `.astype(int)` and print the result. Note what happens to the decimal parts — does it round or truncate?

In [13]:
arr = np.array([1.9, 2.1, 3.7])

# Your code here
arr=arr.astype(int)
print(arr.dtype)

print(arr)


int64
[1 2 3]


**Q13. Memory size of an array**

Create an array of `1000` integers using `np.arange(1000)` with `dtype=np.int8`, and print its `.nbytes`. Then repeat with `dtype=np.int64` and compare the two sizes.

In [14]:
# Your code here



**Q14. Reverse an array**

Given `arr = np.array([1, 2, 3, 4, 5])`, reverse it using slicing (`[::-1]`) — do not use any built-in reverse function.

In [15]:
arr = np.array([1, 2, 3, 4, 5])

# Your code here
print(arr[::-1])


[5 4 3 2 1]


**Q15. Negative indexing**

Given `arr = np.array([15, 22, 8, 47, 3, 91])`, print the last element and the second-to-last element using negative indexing.

In [16]:
arr = np.array([15, 22, 8, 47, 3, 91])

# Your code here
print(arr[-1])
print(arr[-2])


91
3


**Q16. Sum of a 2D array**

Given `matrix = np.array([[2, 4, 6], [1, 3, 5]])`, find the sum of all elements in the array using `np.sum()`.

In [17]:
matrix = np.array([[2, 4, 6], [1, 3, 5]])

# Your code here
print(np.sum(matrix))


21


**Q17. Row-wise and column-wise sums**

Using the same `matrix` from Q16, compute the sum along each column (`axis=0`) and the sum along each row (`axis=1`). Print both.

In [52]:
matrix = np.array([[2, 4, 6], [1, 3, 5]])

# Your code here
sum_of_cols = np.sum(matrix,axis=0)
print(sum_of_cols)

sum_of_rows = np.sum(matrix,axis=1)
print(sum_of_rows)


[ 3  7 11]
[12  9]


**Q18. Min, max, and their indices**

Given `arr = np.array([12, 45, 3, 67, 21, 9])`, find the minimum value, maximum value, and the **index** of each using `np.argmin()` / `np.argmax()`.

In [53]:
arr = np.array([12, 45, 3, 67, 21, 9])

# Your code here
print("Maximum Element ",np.max(arr))
print("Minimum Element",np.min(arr))
print("Max Ele Index",np.argmax(arr))
print("Min Ele Index",np.argmin(arr))


Maximum Element  67
Minimum Element 3
Max Ele Index 3
Min Ele Index 2


**Q19. Mean, median, std, and variance**

Given `arr = np.array([4, 8, 15, 16, 23, 42])`, compute and print its mean, median, standard deviation, and variance.

In [54]:
arr = np.array([4, 8, 15, 16, 23, 42])

# Your code here
print("Mean",np.mean(arr))
print("Median",np.median(arr))
print("Standard Deviation",np.std(arr))
print("variance",np.var(arr))


Mean 18.0
Median 15.5
Standard Deviation 12.315302134607444
variance 151.66666666666666


**Q20. Sort and unique**

Given `arr = np.array([5, 2, 8, 2, 9, 5, 1, 8])`, print the sorted array and the array of unique values.

In [59]:
arr = np.array([5, 2, 8, 2, 9, 5, 1, 8])

# Your code here
arr.sort()
print(arr)

print(np.unique(arr))

[1 2 2 5 5 8 8 9]
[1 2 5 8 9]


---
## 🟡 Section 2: Medium (Q21 – Q40)

These require combining more than one concept — broadcasting, boolean masking, reshaping, stacking, and simple linear algebra. A few functions here are new; each comes with a hint.


**Q21. Row-wise value ramp using broadcasting**

Create a `5x5` array where **every row** is `[0, 1, 2, 3, 4]`, using broadcasting (i.e. do not manually type out all 25 values).

> 💡 **Hint:** Create a 1D array `[0,1,2,3,4]` with `np.arange(5)`, then add it to an array of zeros with shape `(5,5)`. Broadcasting handles the rest.

In [62]:
# Your code here
arr1 = np.arange(5)
arr2 = np.zeros((5,5))

print(arr1)
print(arr2)

print(arr1+arr2)


[0 1 2 3 4]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**Q22. Checkerboard pattern**

Create an `8x8` array of zeros and use slicing to set alternating cells to `1`, producing a checkerboard pattern (like a chessboard).

> 💡 **Hint:** Use step-slicing: `arr[1::2, ::2] = 1` and `arr[::2, 1::2] = 1`.

In [23]:
# Your code here



**Q23. Min-max normalization**

Given `arr = np.array([15, 3, 42, 8, 27])`, normalize it so all values fall between `0` and `1`, using the formula `(x - min) / (max - min)`.

> 💡 **Hint:** Use `np.min()` and `np.max()` on the array directly — no loop needed, this is fully vectorized.

In [63]:
arr = np.array([15, 3, 42, 8, 27])

# Your code here

minVal = np.min(arr)
maxVal = np.max(arr)

ans = (arr - minVal)/(maxVal-minVal)

print(ans)

[0.30769231 0.         1.         0.12820513 0.61538462]


**Q24. Replace odd numbers with -1**

Given `arr = np.arange(1, 11)`, replace every odd number with `-1`, without using a Python `for` loop.

> 💡 **Hint:** Boolean masking: `arr[arr % 2 != 0] = -1`. Indexing an array with a boolean condition selects only the elements where the condition is `True`.

In [64]:
arr = np.arange(1, 11)

# Your code here

for i in range(0,len(arr)):
    if arr[i]%2!=0:
        arr[i]=-1


print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


**Q25. Boolean masking — filter by threshold**

Given `arr = np.array([23, 45, 12, 67, 34, 89, 5])`, extract only the elements greater than `30` into a new array, using boolean masking (not a loop).

In [66]:
arr = np.array([23, 45, 12, 67, 34, 89, 5])

# Your code here

mask = arr > 30

ans = arr[mask]

print(ans)


[45 67 34 89]


**Q26. np.where for conditional replacement**

Given `arr = np.array([4, -2, 7, -9, 15, -1])`, use `np.where()` to create a new array where every negative number is replaced with `0`, and every non-negative number stays the same.

> 💡 **Hint:** `np.where(condition, value_if_true, value_if_false)` returns a new array. Example: `np.where(arr > 0, arr, 0)`.

In [27]:
arr = np.array([4, -2, 7, -9, 15, -1])

# Your code here



**Q27. Reshape a 1D array**

Given `arr = np.arange(1, 13)`, reshape it into a `(3, 4)` 2D array using `.reshape()`. Print the result and its new shape.

> 💡 **Hint:** `.reshape(rows, cols)` — the total number of elements must stay the same (here, 12 = 3×4).

In [28]:
arr = np.arange(1, 13)

# Your code here



**Q28. Flatten a 2D array**

Given `matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])`, flatten it into a single 1D array using `.flatten()` (or `.ravel()`).

In [29]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Your code here



**Q29. Transpose a matrix**

Given `matrix = np.array([[1,2,3],[4,5,6]])` (shape `2x3`), compute its transpose using `.T`, and print the new shape (should be `3x2`).

In [30]:
matrix = np.array([[1,2,3],[4,5,6]])

# Your code here



**Q30. Concatenate arrays**

Given `a = np.array([[1,2],[3,4]])` and `b = np.array([[5,6],[7,8]])`, concatenate them vertically (stacking rows) and separately horizontally (stacking columns), using `np.concatenate()`.

> 💡 **Hint:** Use `np.concatenate((a, b), axis=0)` for vertical stacking and `axis=1` for horizontal.

In [31]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# Your code here



**Q31. vstack and hstack**

Repeat Q30, but this time use `np.vstack()` and `np.hstack()` instead of `np.concatenate()`. Confirm you get the same results.

In [32]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# Your code here



**Q32. Dot product of two vectors**

Given `v1 = np.array([1, 2, 3])` and `v2 = np.array([4, 5, 6])`, compute their dot product using `np.dot()`. Verify by hand: `1*4 + 2*5 + 3*6 = 32`.

> 💡 **Hint:** `np.dot(v1, v2)` or simply `v1 @ v2`.

In [33]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Your code here



**Q33. Matrix multiplication**

Given `A = np.array([[1,2],[3,4]])` and `B = np.array([[5,6],[7,8]])`, compute their matrix product using `np.matmul()` or the `@` operator. Note this is different from element-wise multiplication (`A * B`) — try printing both to see the difference.

In [34]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# Your code here



**Q34. Broadcasting a row vector across a matrix**

Given `M = np.array([[1,2,3],[4,5,6],[7,8,9]])` and `v = np.array([10, 20, 30])`, add `v` to every row of `M` using broadcasting (a single `+` operation, no loop).

In [35]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
v = np.array([10, 20, 30])

# Your code here



**Q35. Finding indices that match a condition**

Given `arr = np.array([3, 7, 1, 9, 4, 7, 2])`, find the indices where the value equals `7`, using `np.where()`.

> 💡 **Hint:** `np.where(arr == 7)` returns a tuple of index arrays — the first element is what you want.

In [36]:
arr = np.array([3, 7, 1, 9, 4, 7, 2])

# Your code here



**Q36. Frequency count with unique**

Given `arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])`, use `np.unique()` with `return_counts=True` to get each unique value along with how many times it occurs. Print them together as pairs.

> 💡 **Hint:** `values, counts = np.unique(arr, return_counts=True)` — then loop over `zip(values, counts)` to print pairs.

In [37]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# Your code here



**Q37. Row-wise and column-wise stats on a matrix**

Given `scores = np.array([[85, 90, 78], [92, 88, 95], [70, 65, 80]])` (rows = students, columns = subjects), compute each student's average score (row-wise mean) and each subject's average score (column-wise mean).

In [38]:
scores = np.array([[85, 90, 78], [92, 88, 95], [70, 65, 80]])

# Your code here



**Q38. Clipping values into a range**

Given `arr = np.array([-5, 12, 45, -20, 8, 100, 3])`, clip all values so they fall within the range `[0, 50]` using `np.clip()`.

> 💡 **Hint:** `np.clip(arr, min_value, max_value)` — anything below the min becomes the min, anything above the max becomes the max.

In [39]:
arr = np.array([-5, 12, 45, -20, 8, 100, 3])

# Your code here



**Q39. Handling NaN values**

Given `arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])`, find the indices of the `NaN` values using `np.isnan()`, then replace them with `0` using boolean masking.

> 💡 **Hint:** `np.isnan(arr)` returns a boolean array marking `True` wherever a value is `NaN`. Use that as a mask: `arr[np.isnan(arr)] = 0`.

In [40]:
arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])

# Your code here



**Q40. Custom function applied element-wise**

Given `arr = np.array([1, 2, 3, 4, 5])`, compute a new array where each element `x` becomes `x**2 + 3*x - 1`, using plain vectorized arithmetic (no loop, no `np.vectorize`).

In [41]:
arr = np.array([1, 2, 3, 4, 5])

# Your code here



---
## 🔴 Section 3: Hard (Q41 – Q50)

These require combining several concepts and a bit of algorithmic thinking. A collapsible solution is provided for each — use it only after a genuine attempt.


**Q41. Euclidean distance between two vectors**

Given `p1 = np.array([1, 2, 3])` and `p2 = np.array([4, 6, 8])`, compute the Euclidean distance between them **without using a loop**.

> 💡 **Hint:** The Euclidean distance formula is `sqrt(sum((p1 - p2)**2))`. Every piece of that formula (subtraction, squaring, summing, square root) has a direct NumPy equivalent.

In [42]:
p1 = np.array([1, 2, 3])
p2 = np.array([4, 6, 8])

# Your code here



<details>
<summary>▶ Click to reveal Solution 41 (try it yourself first!)</summary>

```python
distance = np.sqrt(np.sum((p1 - p2) ** 2))
print(distance)  # 7.0710678118654755
```

**Why it works:** `p1 - p2` is an element-wise subtraction, `** 2` squares each difference, `np.sum()` adds them up, and `np.sqrt()` finishes the formula — all fully vectorized, no loop required.
</details>


**Q42. Second largest value without full sorting**

Given `arr = np.array([12, 45, 3, 89, 45, 67, 23])`, find the second largest **unique** value without using `np.sort()` on the whole array (note the duplicate `45`).

> 💡 **Hint:** Get the unique values first with `np.unique()` — this both removes duplicates and returns them sorted. Then index from the end.

In [43]:
arr = np.array([12, 45, 3, 89, 45, 67, 23])

# Your code here



<details>
<summary>▶ Click to reveal Solution 42 (try it yourself first!)</summary>

```python
unique_vals = np.unique(arr)
second_largest = unique_vals[-2]
print(second_largest)  # 67
```

**Why it works:** `np.unique()` removes duplicates *and* returns the result sorted in ascending order, so the largest value is at index `-1` and the second largest is at index `-2`.
</details>


**Q43. Moving average**

Given `arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])`, compute the moving average with a window size of `3` (i.e., each output value is the average of 3 consecutive elements). Output should have length `8`.

> 💡 **Hint:** Use `np.cumsum()` to get a running total, then the difference between two shifted cumulative sums divided by the window size gives you the moving average in O(n) — no loop over windows needed.

In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window = 3

# Your code here



<details>
<summary>▶ Click to reveal Solution 43 (try it yourself first!)</summary>

```python
def moving_average(a, n=3):
    cumsum = np.cumsum(a)
    cumsum[n:] = cumsum[n:] - cumsum[:-n]
    return cumsum[n - 1:] / n

result = moving_average(arr, 3)
print(result)  # [2. 3. 4. 5. 6. 7. 8. 9.]
```

**Why it works:** `np.cumsum()` gives running totals. Subtracting the cumulative sum shifted by `n` positions from itself leaves you with the sum of just the last `n` elements at each position — which you then divide by `n` to get the average.
</details>


**Q44. RGB to grayscale conversion**

Given a small fake "image" `img = np.random.randint(0, 256, size=(4, 4, 3))` (height, width, RGB channels), convert it to grayscale using the standard luminance formula: `gray = 0.2989*R + 0.5870*G + 0.1140*B`. The result should have shape `(4, 4)`.

> 💡 **Hint:** The three channels live along the last axis (`axis=2`). You can either index `img[:,:,0]`, `img[:,:,1]`, `img[:,:,2]` separately and combine them, or use `np.dot(img, weights)` where `weights = [0.2989, 0.5870, 0.1140]`.

In [45]:
img = np.random.randint(0, 256, size=(4, 4, 3))

# Your code here



<details>
<summary>▶ Click to reveal Solution 44 (try it yourself first!)</summary>

```python
weights = np.array([0.2989, 0.5870, 0.1140])
gray = np.dot(img, weights)
print(gray.shape)  # (4, 4)
print(gray)
```

**Why it works:** `np.dot(img, weights)` treats the last axis of `img` (length 3, the RGB channels) as the axis to contract against `weights` (also length 3), producing a weighted sum per pixel and collapsing the color axis — exactly the grayscale formula, applied to all pixels at once.
</details>


**Q45. Rows containing a specific value**

Given `matrix = np.array([[1,5,9],[2,6,3],[7,8,9],[4,5,6]])`, find all **rows** that contain the value `9` anywhere in that row.

> 💡 **Hint:** First build a boolean mask of where the matrix equals 9 (`matrix == 9`), then use `.any(axis=1)` to check, per row, whether *any* element in that row was `True`. Use that row-mask to index the matrix.

In [46]:
matrix = np.array([[1,5,9],[2,6,3],[7,8,9],[4,5,6]])

# Your code here



<details>
<summary>▶ Click to reveal Solution 45 (try it yourself first!)</summary>

```python
mask = (matrix == 9).any(axis=1)
result = matrix[mask]
print(result)
# [[1 5 9]
#  [7 8 9]]
```

**Why it works:** `matrix == 9` produces a same-shaped boolean array. `.any(axis=1)` collapses each row down to a single `True`/`False` (True if *any* element in that row was True), giving a 1D boolean mask with one entry per row — perfect for indexing the original matrix's rows.
</details>


**Q46. One-hot encoding**

Given `labels = np.array([0, 2, 1, 3, 2, 0])` (4 possible classes: 0-3), convert it into a one-hot encoded 2D array of shape `(6, 4)`, where each row has a `1` in the column matching that label and `0` elsewhere.

> 💡 **Hint:** Create a zeros array of shape `(len(labels), num_classes)`. Then use **fancy indexing**: `one_hot[np.arange(len(labels)), labels] = 1` sets one specific column per row, all at once.

In [47]:
labels = np.array([0, 2, 1, 3, 2, 0])
num_classes = 4

# Your code here



<details>
<summary>▶ Click to reveal Solution 46 (try it yourself first!)</summary>

```python
one_hot = np.zeros((len(labels), num_classes), dtype=int)
one_hot[np.arange(len(labels)), labels] = 1
print(one_hot)
# [[1 0 0 0]
#  [0 0 1 0]
#  [0 1 0 0]
#  [0 0 0 1]
#  [0 0 1 0]
#  [1 0 0 0]]
```

**Why it works:** `np.arange(len(labels))` gives row indices `[0,1,2,3,4,5]` and `labels` gives the column index to set in each of those rows. Pairing them up with fancy indexing (`one_hot[rows, cols] = 1`) sets exactly one cell per row in a single vectorized assignment.
</details>


**Q47. Pairwise distances between points**

Given `points = np.array([[0,0],[3,4],[6,8]])` (3 points in 2D), compute the full `3x3` matrix of pairwise Euclidean distances between every pair of points, without an explicit double `for` loop.

> 💡 **Hint:** Reshape one copy of the array to `(3, 1, 2)` and leave the other as `(3, 2)` — broadcasting will then produce all pairwise differences at once in a `(3, 3, 2)` array. Square, sum along the last axis, and square-root.

In [48]:
points = np.array([[0,0],[3,4],[6,8]])

# Your code here



<details>
<summary>▶ Click to reveal Solution 47 (try it yourself first!)</summary>

```python
diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]
sq_dist = np.sum(diff ** 2, axis=-1)
distances = np.sqrt(sq_dist)
print(distances)
# [[ 0.  5. 10.]
#  [ 5.  0.  5.]
#  [10.  5.  0.]]
```

**Why it works:** `points[:, np.newaxis, :]` reshapes to `(3,1,2)` and `points[np.newaxis, :, :]` reshapes to `(1,3,2)`. Broadcasting these together expands both to `(3,3,2)`, producing every pairwise coordinate difference in one shot. Summing squared differences along the last axis and taking the square root gives the full distance matrix — this is the same broadcasting rule from your basics notebook, just used across two new axes.
</details>


**Q48. Finding local maxima (peaks) in a 1D array**

Given `arr = np.array([1, 3, 7, 2, 9, 4, 5, 8, 2, 6])`, find the indices of all **local maxima** — points that are strictly greater than both neighbors (ignore the first and last elements, which have no two neighbors).

> 💡 **Hint:** Compare `arr[1:-1]` (the middle elements) against `arr[:-2]` (their left neighbors) and `arr[2:]` (their right neighbors) simultaneously using boolean `&`. The resulting True positions, shifted by 1, are your peak indices.

In [49]:
arr = np.array([1, 3, 7, 2, 9, 4, 5, 8, 2, 6])

# Your code here



<details>
<summary>▶ Click to reveal Solution 48 (try it yourself first!)</summary>

```python
is_peak = (arr[1:-1] > arr[:-2]) & (arr[1:-1] > arr[2:])
peak_indices = np.where(is_peak)[0] + 1
print(peak_indices)   # [2 4 7]
print(arr[peak_indices])  # [7 9 8]
```

**Why it works:** Slicing the array three different ways (`[1:-1]`, `[:-2]`, `[2:]`) lines up every middle element with its left and right neighbor in parallel, so the two comparisons and the `&` all happen element-wise across the whole array at once. Adding `1` corrects the index offset introduced by starting the slice at position `1`.
</details>


**Q49. Z-score standardization per column**

Given `data = np.array([[1, 200], [2, 300], [3, 100], [4, 400]])`, standardize **each column independently** so that every column has mean `0` and standard deviation `1` (the z-score formula: `(x - mean) / std`).

> 💡 **Hint:** Compute the mean and std along `axis=0` (per column) — this gives you a 1D array of length 2 (one value per column) that will automatically broadcast against the `(4, 2)` matrix.

In [50]:
data = np.array([[1, 200], [2, 300], [3, 100], [4, 400]], dtype=float)

# Your code here



<details>
<summary>▶ Click to reveal Solution 49 (try it yourself first!)</summary>

```python
col_mean = data.mean(axis=0)
col_std = data.std(axis=0)
standardized = (data - col_mean) / col_std
print(standardized)
print(standardized.mean(axis=0))  # ~[0. 0.]
print(standardized.std(axis=0))   # [1. 1.]
```

**Why it works:** `data.mean(axis=0)` and `data.std(axis=0)` collapse along the rows, giving one mean and one std per column — shape `(2,)`. Subtracting and dividing a `(4,2)` array by two `(2,)` arrays triggers broadcasting, applying each column's own mean/std to every row in that column simultaneously.
</details>


**Q50. Common rows between two 2D arrays**

Given `A = np.array([[1,2],[3,4],[5,6],[7,8]])` and `B = np.array([[3,4],[7,8],[9,10]])`, find the rows that appear in **both** `A` and `B`.

> 💡 **Hint:** A plain `np.intersect1d()` only works on 1D arrays. One clean trick: convert each row into a single value/tuple that uniquely represents it (e.g. using a structured view or `set` of tuples), find the intersection, then map back.

In [51]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
B = np.array([[3,4],[7,8],[9,10]])

# Your code here



<details>
<summary>▶ Click to reveal Solution 50 (try it yourself first!)</summary>

```python
A_set = set(map(tuple, A))
B_set = set(map(tuple, B))
common = np.array(sorted(A_set & B_set))
print(common)
# [[3 4]
#  [7 8]]
```

**Why it works:** NumPy arrays aren't hashable, but tuples are — so converting each row into a tuple (`map(tuple, A)`) lets us drop rows into ordinary Python `set`s, where `&` performs a fast intersection. This is a good example of stepping outside pure NumPy when the built-in tools don't directly support the operation (2D array intersection), then converting back to an array at the end.
</details>


---
## Wrap-Up

Once you've completed all 50 questions:

- Go back through the **Hard** section and try to rewrite at least 2 solutions from memory, without peeking.
- Notice how often the answer to "how do I avoid a loop here?" was **broadcasting** or **boolean masking** — this pattern shows up constantly in real NumPy/pandas code.
- If a question felt unclear or a hint didn't help, that's useful signal — revisit that specific NumPy function's documentation (`np.info(function_name)` works right inside a notebook).

**Submission note:** Run `Kernel → Restart & Run All` and make sure every cell executes without errors before submitting.
