<h3>NumPy (short form of Numerical Python) is an open-source Python library used for
numerical computing. It provides tools for working efficiently with arrays, matrices, and
mathematical functions.</h3>
<h3>NumPy introduces a new data structure called the ndarray (n-dimensional array),
which is much faster and more memory-efficient than Python’s built-in lists for
numerical operations.</h3>

In [1]:
import numpy as np

arr = np.array([1,2,3,"Hello"])
arr

array(['1', '2', '3', 'Hello'], dtype='<U21')

In [2]:
#To get size of array
arr.nbytes

336

In [3]:
#Type of array
type(arr)

numpy.ndarray

In [5]:
#Shape of array returns in tuple the dimension
arr.shape

(4,)

<h2>Using Bultin Functions lets create ndarray</h2>

In [13]:
#Create arr of (row,col) dimension with 0 values

zerosArr = np.zeros((2,3))
print(zerosArr)

#Creating arr of (row,col) dimension with 1 value

oneArr = np.ones((3,3))
print(oneArr)


#Creating arr of (row,col) dimension with any value

mat = np.full((2,2),5)
print(mat)

#Creating Identity matrix
id_mat = np.eye(3)
print(id_mat)

arr5 = np.arange(1, 20, 2) # Elements in range(1, 20)
print(arr5, arr5.shape)
arr6 = np.linspace(0, 10, 5) # Evenly spaced array
print(arr6, arr6.shape)
print(arr6.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  3  5  7  9 11 13 15 17 19] (10,)
[ 0.   2.5  5.   7.5 10. ] (5,)
1



<h4>💡 In short:</h4>
<h5>The formal meaning: (3,3,4) → lengths along axes 0, 1, 2.</h5>
<h5>The analogy explanation: “blocks, rows, columns” → just a way to help you visualize the 3D shape.</h5>

In [16]:
import numpy as np
arr = np.zeros((3, 3, 4))


In [17]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
#Create arr of (row,col) dimension with 0 values

zerosArr = np.zeros((2,3,3))
print(zerosArr)

#Creating arr of (row,col) dimension with 1 value

oneArr = np.ones((3,3,3))
print(oneArr)


#Creating arr of (row,col) dimension with any value

mat = np.full((2,2,6),5)
print(mat)

#Creating Identity matrix
id_mat = np.eye(3)
print(id_mat)

arr5 = np.arange(1, 20, 2) # Elements in range(1, 20)
print(arr5, arr5.shape)
arr6 = np.linspace(0, 10, 5) # Evenly spaced array
print(arr6, arr6.shape)
print(arr6.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[5 5 5 5 5 5]
  [5 5 5 5 5 5]]

 [[5 5 5 5 5 5]
  [5 5 5 5 5 5]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  3  5  7  9 11 13 15 17 19] (10,)
[ 0.   2.5  5.   7.5 10. ] (5,)
1
